
CHECKER_TESTLIST := \
	basic_prefetch_gen

ifeq ($(UCE_P),1)
CE := UCE
else
CE := CCE
endif

ifeq ($(WT_P),1)
CA := WT
else
CA := WB
endif

run_testlist.%:
	$(MAKE) build.$* TAG=$(CE).$(CA)
	$(MAKE) $(addsuffix .$*, $(addprefix run_test.$(CE).$(CA).,$(CHECKER_TESTLIST)))

# We can trim this up a bit when we have custom configs
run_test.%:
	$(eval override CE    := $(word 1,$(subst .,  ,$*)))
	$(eval override CA    := $(word 2,$(subst .,  ,$*)))
	$(eval override PROG  := $(word 3,$(subst .,  ,$*)))
	$(eval override TS    := $(word 4,$(subst .,  ,$*)))
	$(MAKE) sim.$(TS) PROG=$(PROG) TAG=$(CE).$(CA)
