#
#   trace_gen_rpt.py
#

# packets: [command, output, input]: [command, eff_addr, stride, pc, start_discovery, confirm_discovery, w_v_i, pc_i, eff_addr_i]

from rpt import SVElement, Rpt

class TraceGen:

  # constructor
  def __init__(self, rpt_sets_p, stride_width_p, vaddr_width_p, rpt_ctr_width_p):
    self.sets         = rpt_sets_p
    self.stride_width = stride_width_p
    self.vaddr_width  = vaddr_width_p
    self.ctr_width    = rpt_ctr_width_p

    self.rpt = Rpt(rpt_sets_p, stride_width_p, vaddr_width_p, rpt_ctr_width_p)

    self.input_width = 1 + vaddr_width_p*2 #w_v_i, pc_i, eff_addr_i
    self.output_width= self.vaddr_width + self.stride_width + self.vaddr_width + 2 #eff_addr, stride, pc, start_discovery, confirm_discovery
    self.packet_len  = self.input_width + self.output_width


  # print header
  def print_header(self):
    header = "// generated by trace_gen.py \n"
    header += "// packet_len = " + str(self.packet_len) + "\n" 
    return header

  def put(self, pc, eff_addr):
    if(not isinstance(pc, SVElement)):
      pc = SVElement(pc)
    if(not isinstance(eff_addr, SVElement)):
      eff_addr = SVElement(eff_addr)
    assert(len(pc)<=self.vaddr_width)
    assert(len(eff_addr)<=self.vaddr_width)
    # Normalize widths
    pc        = SVElement("0"*(self.vaddr_width - len(pc))) + pc
    eff_addr  = SVElement("0"*(self.vaddr_width - len(eff_addr))) + eff_addr

    retval = "0001_" + "0"*self.output_width + "_" + "1_" + str(pc) + "_" + str(eff_addr) + "\n"
    if self.rpt.put(pc, eff_addr):
      # print(self.rpt.snapshot_verbose() + ", start/confirm: " + str(self.rpt.discovery_mode()))
      retval += "0010_" + self.rpt.snapshot() + "_" + str(self.rpt.discovery_mode()) + "_" + "0"*self.input_width + "\n"
    return retval

  # wait for a number of cycles
  # num_cycles: number of cycles to wait.
  def wait(self, num_cycles):
    command = "0110_" + format(num_cycles, "0" + str(self.packet_len) + "b") + "\n"
    command += "0101_" + (self.packet_len)*"0" + "\n"
    return command

  # finish trace
  def test_finish(self):
    command = "// FINISH \n"
    command += self.wait(8)
    command += "0100_" + (self.packet_len)*"0" + "\n"
    return command

  def test_done(self):
    command = "// DONE \n"
    command += self.wait(8)
    command += "0011_" + (self.packet_len)*"0" + "\n"
    return command

  # wait for a single cycle
  def nop(self):
    return "0000_" + "0"*(self.packet_len) + "\n"
  
  # print comments in the trace file
  def print_comment(self, comment):
    return "// " + comment + "\n"

  def reset(self):
    self.rpt.reset()
