#
#   trace_gen_prefetch_gen.py
#

import numpy as np

class TraceGen:

  # constructor
  def __init__(self, loop_range_width_p, stride_width_p, vaddr_width_p, dispatch_pkt_width_p, block_width_p):
    self.loop_range_width_p = loop_range_width_p
    self.stride_width_p = stride_width_p
    self.vaddr_width_p = vaddr_width_p
    self.dispatch_pkt_width_p = dispatch_pkt_width_p
    self.block_width_p = block_width_p
    # dispatch_pkt_width_p is wider than the rest combined and is the only contents of the expected output for matching
    self.packet_len = dispatch_pkt_width_p
    self.junk_width = dispatch_pkt_width_p - (loop_range_width_p + vaddr_width_p*2 + stride_width_p)
    if (self.junk_width < 0):
      raise ValueError("Packet larger than dispatch packet width")
    

  # print header
  def print_header(self):
    header = "// generated by trace_gen.py \n"
    header += "// packet_len = " + str(self.packet_len) + "\n" 
    return header

  # send prefetch info
  def send_pref_info(self, pc, eff_addr, loop_counter, stride):
    packet = "0001_"

    packet += format(0, "0" + str(self.junk_width)+"b")+ "_"

    packet += format(pc, "0"+str(self.vaddr_width_p)+"b") + "_"

    packet += format(eff_addr, "0"+str(self.vaddr_width_p+"b")) + "_"

    packet += format(loop_counter, "0"+str(self.loop_range_width_p)+"b") + "_"

    packet += format(stride, "0"+str(self.stride_width_p)+"b") + "\n"
    return packet

  def format_dispatch_pkt(self, pc, eff_addr):
    packet = ""
    instr = "00000000000100000110000000010011"
    packet += "10000" + format(pc, "0"+str(self.vaddr_width_p+"b")) + "_" + instr + "_" + format(eff_addr, "0"+str(self.vaddr_width_p+"b")) + "_" + "001000000" + "000000000001000001110010" + "01" + "000" + "000000" + "000000" + "0001000000"
    return packet

  def recv_dispatch_pkts(self, pc, eff_addr, stride, loop_counter):
    packet_set = ""
    prev_eff_addr = eff_addr
    while loop_counter > 0:
      loop_counter -= 1
      eff_addr += stride
      if not (prev_eff_addr/self.block_width_p == eff_addr/self.block_width_p):
        #send dispatch packet
        packet_set += "0010" + self.format_dispatch_pkt(pc, eff_addr) + "\n"
      prev_eff_addr = eff_addr
    return packet_set

  # receive data
  # data: expected data
  def recv_data(self, data):
    packet = "0010_"
    bin_data = np.binary_repr(data, 64)
    packet += "0" + "0"*(self.ptag_width_p) + "_" + "0"*(self.opcode_width_p) + "_" + "0"*(self.offset_width_p) + "_" + "00" + bin_data + "\n"
    return packet

  # wait for a number of cycles
  # num_cycles: number of cycles to wait.
  def wait(self, num_cycles):
    command = "0110_" + format(num_cycles, "0" + str(self.packet_len) + "b") + "\n"
    command += "0101_" + (self.packet_len)*"0" + "\n"
    return command

  # finish trace
  def test_finish(self):
    command = "// FINISH \n"
    command += self.wait(8)
    command += "0100_" + (self.packet_len)*"0" + "\n"
    return command

  def test_done(self):
    command = "// DONE \n"
    command += self.wait(8)
    command += "0011_" + (self.packet_len)*"0" + "\n"
    return command

  # wait for a single cycle
  def nop(self):
    return "0000_" + "0"*(self.packet_len) + "\n"
  
  # print comments in the trace file
  def print_comment(self, comment):
    return "// " + comment + "\n"
