#
#   trace_gen_prefetch_gen.py
#

class TraceGen:

  # constructor
  def __init__(self, loop_range_width_p, stride_width_p, vaddr_width_p, block_width_p, instr_width_p, decode_width_p):
    self.loop_range_width_p = loop_range_width_p
    self.stride_width_p = stride_width_p
    self.vaddr_width_p = vaddr_width_p
    self.block_width_p = block_width_p

    self.input_width = 1 + vaddr_width_p*2 + stride_width_p + loop_range_width_p # commit_v, pc, eff addr, stride, loop count
    self.output_width= vaddr_width_p + instr_width_p + decode_width_p # eff addr, instr, decode
    self.packet_len  = self.input_width + self.output_width
    self.delay_cycles= 2


  # print header
  def print_header(self):
    header = "// generated by trace_gen.py \n"
    header += "// packet_len = " + str(self.packet_len) + "\n" 
    return header

  

  # wait for a number of cycles
  # num_cycles: number of cycles to wait.
  def wait(self, num_cycles):
    command = "0110_" + format(num_cycles, "0" + str(self.packet_len) + "b") + "\n"
    command += "0101_" + (self.packet_len)*"0" + "\n"
    return command

  # finish trace
  def test_finish(self):
    command = "// FINISH \n"
    command += self.wait(8)
    command += "0100_" + (self.packet_len)*"0" + "\n"
    return command

  def test_done(self):
    command = "// DONE \n"
    command += self.wait(8)
    command += "0011_" + (self.packet_len)*"0" + "\n"
    return command

  # wait for a single cycle
  def nop(self):
    return "0000_" + "0"*(self.packet_len) + "\n"
  
  # print comments in the trace file
  def print_comment(self, comment):
    return "// " + comment + "\n"
