#
#   trace_gen_prefetch_gen.py
#

class TraceGen:

  # constructor
  def __init__(self, loop_range_width_p, stride_width_p, vaddr_width_p, block_width_p, instr_width_p, decode_width_p):
    self.loop_range_width_p = loop_range_width_p
    self.stride_width_p = stride_width_p
    self.vaddr_width_p = vaddr_width_p
    self.block_width_p = block_width_p

    self.input_width = vaddr_width_p*2 + stride_width_p + loop_range_width_p
    self.output_width= vaddr_width_p + instr_width_p + decode_width_p
    self.packet_len  = self.input_width + self.output_width


  # print header
  def print_header(self):
    header = "// generated by trace_gen.py \n"
    header += "// packet_len = " + str(self.packet_len) + "\n" 
    return header

  # send prefetch info
  def send_pref_info(self, pc, eff_addr, loop_counter, stride):
    packet = "0001_"

    packet += "0"*self.output_width + "_"

    packet += format(0, "0" + str(self.junk_width)+"b")+ "_"

    packet += format(pc, "0"+str(self.vaddr_width_p)+"b") + "_"

    packet += format(eff_addr, "0"+str(self.vaddr_width_p+"b")) + "_"

    packet += format(loop_counter, "0"+str(self.loop_range_width_p)+"b") + "_"

    packet += format(stride, "0"+str(self.stride_width_p)+"b") + "\n"
    return packet

  def format_dispatch_pkt(self, eff_addr):
    packet = ""
    imm11to5 = "0000000"
    rs2 = "00001"
    rs1 = "00000"
    funct3 = "110"
    imm4to0 = "00000"
    opcode = "0010011"
    instr = imm11to5 + rs2 + rs1 + funct3 + imm4to0 + opcode
    decode = "00100000000000000000100000101001101000000000000001000000"
    packet += instr + "_" + decode + "_" + format(eff_addr, "0"+str(self.vaddr_width_p+"b")) + "_" + "0"*self.input_width
    return packet

  def recv_dispatch_pkts(self, pc, eff_addr, stride, loop_counter):
    packet_set = ""
    prev_eff_addr = eff_addr
    while loop_counter > 0:
      loop_counter -= 1
      eff_addr += stride
      if not (prev_eff_addr/self.block_width_p == eff_addr/self.block_width_p):
        #send dispatch packet
        packet_set += "0010_" + self.format_dispatch_pkt(pc, eff_addr) + "\n"
      prev_eff_addr = eff_addr
    return packet_set

  # wait for a number of cycles
  # num_cycles: number of cycles to wait.
  def wait(self, num_cycles):
    command = "0110_" + format(num_cycles, "0" + str(self.packet_len) + "b") + "\n"
    command += "0101_" + (self.packet_len)*"0" + "\n"
    return command

  # finish trace
  def test_finish(self):
    command = "// FINISH \n"
    command += self.wait(8)
    command += "0100_" + (self.packet_len)*"0" + "\n"
    return command

  def test_done(self):
    command = "// DONE \n"
    command += self.wait(8)
    command += "0011_" + (self.packet_len)*"0" + "\n"
    return command

  # wait for a single cycle
  def nop(self):
    return "0000_" + "0"*(self.packet_len) + "\n"
  
  # print comments in the trace file
  def print_comment(self, comment):
    return "// " + comment + "\n"
